### ISSUE TITLE
can't create repo

### ISSUE THREAD

**Issue by shinriyo** [jazzyb/sqlite_ecto#49]
I did the command

```
mix ecto.gen.repo Blog.Repo
```

error is 

```
== Compilation error on file lib/sqlite_ecto.ex ==
** (CompileError) lib/sqlite_ecto.ex:41: no super defined for load/2 in module Sqlite.Ecto. Overridable functions available are: autogenerate/1, delete/4, dumpers/2, ensure_all_started/2, execute/6, execute_ddl/3, insert/5, insert_all/6, loaders/2, prepare/2, update/6
    lib/sqlite_ecto.ex:40: (module)
```

my `mix.exs` file is 

```
  defp deps do
    [{:phoenix, "~> 1.2.1"},
     {:phoenix_pubsub, "~> 1.0"},
     {:poison, "~> 2.1", override: true},
     {:ecto, "~> 2.0", override: true},
     {:phoenix_ecto, "~> 3.0"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.6"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.11"},
     {:sqlite_ecto, "~> 1.0.2"},
     {:cowboy, "~> 1.0"}]
  end
```

**Comment by philipgiuliani** [comment]
I'm sure you already found out, but this project is not working with Ecto 2.0.
There is another issue for this problem: https://github.com/jazzyb/sqlite_ecto/issues/47
